name: animated_fixed_snack_bar
owner: suica.dev
description: "A widget to display fixed snack bar with the animation from top to down."
version: 1.0.0

environment:
  sdk: ">=3.0.9 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
